import { chromium } from '@playwright/test';
import { spawn } from 'node:child_process';
const server = spawn('npx', ['vite', 'preview', '--port', '4176', '--strictPort'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 2500));
const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
await page.goto('http://localhost:4176/OhCanada/?e2e=1&preset=minimal', { waitUntil: 'load' });
await page.getByTestId('menu-new').waitFor({ timeout: 120000 });
await page.getByTestId('menu-new').click();
await page.getByTestId('creator-confirm').click();
await page.waitForFunction(() => !!document.querySelector('[data-screen="hud"]') && !document.querySelector('[data-screen="loading"]'), null, { timeout: 300000 });
const bindings = await page.evaluate(() => window.__truenorth.state().settings.keyBindings);
console.log('bindings', JSON.stringify(bindings));
await page.keyboard.press('KeyW');
await page.waitForTimeout(3000);
console.log('journal open after W:', await page.locator('[data-screen="journal"]').count());
await page.keyboard.press('KeyJ');
await page.waitForTimeout(3000);
console.log('journal open after J:', await page.locator('[data-screen="journal"]').count());
await browser.close(); server.kill(); process.exit(0);
